### ISSUE TITLE
[RFC] Split into PSR-15 middleware and stand-alone app

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-http-api#34]
I'd like to split the package. The API middlewares should be moved to a library package so that you can composer install them in your own PSR-7/PSR-15 driven application and mix them with auth middleware and so on.

This package can be turned into a skeleton that uses the lib and provides a ready-to-use expressive app as it is now.

The lib can be called `event-store-http-middleware` or we integrate it in the [http-middleware](https://github.com/prooph/http-middleware) package.

Thoughts @prolic @sandrokeil @oqq @basz

**Comment by prolic** [comment]
All for it. Let's do a new package and not mix with the existing middleware
package.

**Comment by basz** [comment]
No preference, so go for it
